// <auto-generated />
using System;
using Fat_Pig_Invest_Stock_Wallet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fat_Pig_Invest_Stock_Wallet.Migrations
{
    [DbContext(typeof(FatPigInvestContext))]
    [Migration("20221009182536_MigracaoInicial")]
    partial class MigracaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Fat_Pig_Invest_Stock_Wallet.Models.Acao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Acoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmpresaId = 1,
                            Ticker = "ITSA3"
                        },
                        new
                        {
                            Id = 2,
                            EmpresaId = 1,
                            Ticker = "ITSA4"
                        },
                        new
                        {
                            Id = 3,
                            EmpresaId = 2,
                            Ticker = "PETR3"
                        },
                        new
                        {
                            Id = 4,
                            EmpresaId = 2,
                            Ticker = "PETR4"
                        },
                        new
                        {
                            Id = 5,
                            EmpresaId = 3,
                            Ticker = "OIBR3"
                        },
                        new
                        {
                            Id = 6,
                            EmpresaId = 4,
                            Ticker = "SANB11"
                        },
                        new
                        {
                            Id = 7,
                            EmpresaId = 5,
                            Ticker = "TAEE11"
                        });
                });

            modelBuilder.Entity("Fat_Pig_Invest_Stock_Wallet.Models.Corretora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Corretoras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "FATPIG INVEST DVTM LTDA"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "NU INVEST CORRETORA DE VALORES S.A"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "XP INVESTIMENTOS CCTVM S/A"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "MODAL DTVM LTDA"
                        });
                });

            modelBuilder.Entity("Fat_Pig_Invest_Stock_Wallet.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cnpj = "61.532.644/0001-15",
                            Nome = "ITAUSA"
                        },
                        new
                        {
                            Id = 2,
                            Cnpj = "33.000.167/0001-01",
                            Nome = "PETROBRAS"
                        },
                        new
                        {
                            Id = 3,
                            Cnpj = "76.535.764/0001-43",
                            Nome = "OI SA"
                        },
                        new
                        {
                            Id = 4,
                            Cnpj = "90.400.888/0001-42",
                            Nome = "SANTANDER BR"
                        },
                        new
                        {
                            Id = 5,
                            Cnpj = "07.859.971/0001-30",
                            Nome = "TAESA"
                        });
                });

            modelBuilder.Entity("Fat_Pig_Invest_Stock_Wallet.Models.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Corretagem")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("CorretoraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPregao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Emolumentos")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("NumeroNota")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxaLiquidacao")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CorretoraId");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("Fat_Pig_Invest_Stock_Wallet.Models.Ordem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AcaoId")
                        .HasColumnType("int");

                    b.Property<int>("NotaId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("TipoOrdem")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.HasKey("Id");

                    b.HasIndex("AcaoId");

                    b.HasIndex("NotaId");

                    b.ToTable("Ordens");
                });

            modelBuilder.Entity("Fat_Pig_Invest_Stock_Wallet.Models.Provento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AcaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataProvento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TipoProventoId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorProvento")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("AcaoId");

                    b.HasIndex("TipoProventoId");

                    b.ToTable("Proventos");
                });

            modelBuilder.Entity("Fat_Pig_Invest_Stock_Wallet.Models.TipoProvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposProvento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Dividendos"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Juros sobre Capital Próprio (JCP)"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Rendimentos FIIs"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Outros"
                        });
                });

            modelBuilder.Entity("Fat_Pig_Invest_Stock_Wallet.Models.Acao", b =>
                {
                    b.HasOne("Fat_Pig_Invest_Stock_Wallet.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Fat_Pig_Invest_Stock_Wallet.Models.Nota", b =>
                {
                    b.HasOne("Fat_Pig_Invest_Stock_Wallet.Models.Corretora", "Corretora")
                        .WithMany()
                        .HasForeignKey("CorretoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corretora");
                });

            modelBuilder.Entity("Fat_Pig_Invest_Stock_Wallet.Models.Ordem", b =>
                {
                    b.HasOne("Fat_Pig_Invest_Stock_Wallet.Models.Acao", "Acao")
                        .WithMany()
                        .HasForeignKey("AcaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fat_Pig_Invest_Stock_Wallet.Models.Nota", "Nota")
                        .WithMany("Ordens")
                        .HasForeignKey("NotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acao");

                    b.Navigation("Nota");
                });

            modelBuilder.Entity("Fat_Pig_Invest_Stock_Wallet.Models.Provento", b =>
                {
                    b.HasOne("Fat_Pig_Invest_Stock_Wallet.Models.Acao", "Acao")
                        .WithMany()
                        .HasForeignKey("AcaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fat_Pig_Invest_Stock_Wallet.Models.TipoProvento", "TipoProvento")
                        .WithMany()
                        .HasForeignKey("TipoProventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acao");

                    b.Navigation("TipoProvento");
                });

            modelBuilder.Entity("Fat_Pig_Invest_Stock_Wallet.Models.Nota", b =>
                {
                    b.Navigation("Ordens");
                });
#pragma warning restore 612, 618
        }
    }
}
